version: "3.8"

services:
  zookeeper:
    image: quay.io/debezium/zookeeper:2.3
    container_name: zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    networks:
      - ui-network
  kafka:
    image: quay.io/debezium/kafka:2.3
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
    networks:
      - ui-network
# MySQL - для примера
  mysql: # тут лежит база
    image: quay.io/debezium/example-mysql:2.3
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=debezium 
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
    networks:
      - ui-network
  mysqlterm: # тут подключаемся к базе
    image: mysql:8.0
    container_name: mysqlterm
    depends_on:
      - mysql
    links:
      - mysql:mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=True
    networks:
      - ui-network
# Kafka connect: сюда регать коннекторы
  connect:
    image: quay.io/debezium/connect:2.3
    container_name: connect
    ports:
      - "8083:8083"
    depends_on:
      - kafka
      - mysql
    links:
      - kafka:kafka
      - mysql:mysql
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_source_connect_statuses
    networks:
      - ui-network
# kafka event listner
  watcher:
    image: quay.io/debezium/kafka:2.3
    container_name: watcher
    depends_on:
      - zookeeper
      - kafka
    links:
      - zookeeper:zookeeper
      - kafka:kafka
    command:  watch-topic -a -k dbserver1.inventory.customers
    environment: 
      - ZOOKEEPER_CONNECT=zookeeper:2181 #  этих ребят надо указывать явно
      - KAFKA_BROKER=kafka:9092
      - KAFKA_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    networks:
      - ui-network

networks:
  ui-network: