version: "3.8"

services:
  zookeeper:
    image: quay.io/debezium/zookeeper:2.3
    container_name: zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    networks:
      - ui-network
  kafka:
    image: quay.io/debezium/kafka:2.3
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
    networks:
      - ui-network
# MySQL - для примера
  mysql: # тут лежит база
    image: quay.io/debezium/example-mysql:2.3
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=debezium 
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
    networks:
      - ui-network
  mysqlterm: # тут подключаемся к базе
    image: mysql:8.0
    container_name: mysqlterm
    depends_on:
      - mysql
    links:
      - mysql:mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=True
    networks:
      - ui-network
networks:
  ui-network: